version: '3.8'
services:
    db:
        image: postgres:14-alpine
        restart: "on-failure"
        env_file:
            - ./.env
        volumes:
            - "/opt/app/pg/data:/var/lib/postgresql/data"
            - "/opt/app/pg/init:/docker-entrypoint-initdb.d"
        ports:
            - "5432:5432"
    bot:
        build: .
        restart: "unless-stopped"
        env_file: .env
        command: sh -c "alembic upgrade head && python3 -m bot"
        depends_on:
            - db
