version: "3.9"
services:
    db:
        image: postgres:14.8-alpine3.18
        env_file: .env
        volumes:
        - habrdb-data:/var/lib/postgresql/data
        ports:
        - "5432:5432"
    bot:
        build: .
        restart: "unless-stopped"
        env_file: .env
        command: sh -c "alembic upgrade head && python3 -m bot"
        depends_on:
            - db
volumes:
    habrdb-data:
