version: "3.9"
services:
    db:
        image: postgres:16.0-alpine3.18
        restart: "always"
        env_file: envs/db.env
        volumes:
        - adbotdb-data:/var/lib/postgresql/data
        ports:
        - "5432:5432"
    bot:
        build: .
        restart: "unless-stopped"
        env_file: envs/bot.env
        command: sh -c "alembic upgrade head && python3 -m bot"
        depends_on:
            - db
volumes:
    adbotdb-data:
