"""initial

Revision ID: 02922d84fff3
Revises: 
Create Date: 2023-11-07 18:17:03.010869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02922d84fff3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('username', sa.CHAR(length=40), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('advertisements',
    sa.Column('advertisement_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.CHAR(length=40), nullable=False),
    sa.Column('photo', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('advertisement_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advertisements')
    op.drop_table('users')
    # ### end Alembic commands ###
